// <auto-generated />
using System;
using Backend.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Infrastructure.Migrations
{
    [DbContext(typeof(BackendContext))]
    [Migration("20241027001220_Motorista")]
    partial class Motorista
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Domain.Entities.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("email");

                    b.Property<int?>("IdEscalaTrabalho")
                        .HasColumnType("integer")
                        .HasColumnName("id_escala_trabalho");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_alteracao");

                    b.Property<int?>("IdUsuarioCadastro")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_cadastro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("StatusTreinamento")
                        .HasColumnType("integer")
                        .HasColumnName("status_treinamento");

                    b.HasKey("Id");

                    b.HasIndex("IdEscalaTrabalho");

                    b.HasIndex("IdUsuarioAlteracao");

                    b.HasIndex("IdUsuarioCadastro");

                    b.ToTable("motorista");
                });

            modelBuilder.Entity("Backend.Domain.Entities.MotoristaEscalaTrabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime>("HorarioFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horario_fim");

                    b.Property<DateTime>("HorarioInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("horario_inicio");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_alteracao");

                    b.Property<int?>("IdUsuarioCadastro")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_cadastro");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioAlteracao");

                    b.HasIndex("IdUsuarioCadastro");

                    b.ToTable("motorista_escala_trabalho");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_alteracao");

                    b.Property<int?>("IdUsuarioCadastro")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_cadastro");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioAlteracao");

                    b.HasIndex("IdUsuarioCadastro");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<string>("Cor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cor");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_alteracao");

                    b.Property<int?>("IdUsuarioCadastro")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_cadastro");

                    b.Property<double?>("KmLitro")
                        .HasColumnType("double precision")
                        .HasColumnName("km_litro");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("placa");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioAlteracao");

                    b.HasIndex("IdUsuarioCadastro");

                    b.ToTable("veiculo");
                });

            modelBuilder.Entity("Backend.Domain.Entities.VeiculoLicenciamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_validade");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_alteracao");

                    b.Property<int?>("IdUsuarioCadastro")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_cadastro");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_veiculo");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioAlteracao");

                    b.HasIndex("IdUsuarioCadastro");

                    b.HasIndex("IdVeiculo");

                    b.ToTable("veiculo_licenciamento");
                });

            modelBuilder.Entity("Backend.Domain.Entities.VeiculoManutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("diagnostico");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_alteracao");

                    b.Property<int?>("IdUsuarioCadastro")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_cadastro");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_veiculo");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioAlteracao");

                    b.HasIndex("IdUsuarioCadastro");

                    b.HasIndex("IdVeiculo");

                    b.ToTable("veiculo_manutencao");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Motorista", b =>
                {
                    b.HasOne("Backend.Domain.Entities.MotoristaEscalaTrabalho", "EscalaTrabalho")
                        .WithMany()
                        .HasForeignKey("IdEscalaTrabalho");

                    b.HasOne("Backend.Domain.Entities.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAlteracao");

                    b.HasOne("Backend.Domain.Entities.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCadastro");

                    b.Navigation("EscalaTrabalho");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Backend.Domain.Entities.MotoristaEscalaTrabalho", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAlteracao");

                    b.HasOne("Backend.Domain.Entities.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCadastro");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAlteracao");

                    b.HasOne("Backend.Domain.Entities.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCadastro");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAlteracao");

                    b.HasOne("Backend.Domain.Entities.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCadastro");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCadastro");
                });

            modelBuilder.Entity("Backend.Domain.Entities.VeiculoLicenciamento", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAlteracao");

                    b.HasOne("Backend.Domain.Entities.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCadastro");

                    b.HasOne("Backend.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("IdVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCadastro");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Backend.Domain.Entities.VeiculoManutencao", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAlteracao");

                    b.HasOne("Backend.Domain.Entities.Usuario", "UsuarioCadastro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCadastro");

                    b.HasOne("Backend.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("IdVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCadastro");

                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
